### ISSUE TITLE
Move dashboard-api from dedicated VM to existing VMs running deriva stack

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard-api#10]
For Epic2 the end user's browser needs to be able to make requests against the dashboard API, with appropriate authentication and authorization for requests that require it (e.g., a DCC curator validating a pre-release dataset.) It's likely that this will be done by mapping a top-level path prefix via the AWS ELB path rules.

**Comment by mikedarcy** [comment]
I've implemented the changes required to support this in https://github.com/nih-cfde/dashboard-api/tree/epic2_202101. I've also deployed that branch to the dev environment (app-dev.nih-cfde.org) backend API systems, and set both the dashboard-api and dashboard HTML/JS components to be included in the automatic daily build and deployment in the dev environment.
