### ISSUE TITLE
Impose authorization on API endpoints that require catalog ID

### ISSUE THREAD

**Issue by victor73** [nih-cfde/dashboard-api#12]
After discussing the placement of the API, the group agreed to keep it in the private subnet of the VPC. Requests to the API would therefore come from the dashboard front-end, implemented with Python/flask. The group also felt that instead of handling the authentication/authorization completely, the dashboard should simply pass the auth information to the API.

**Comment by mikedarcy** [comment]
This has been implemented in https://github.com/nih-cfde/dashboard-api/tree/epic2_202101

**Comment by victor73** [comment]
@mikedarcy Is this closable then?

**Comment by mikedarcy** [comment]
I think so but was hoping to run it through a bit more QA first.
