### ISSUE TITLE
Extend API to provide endpoint to retrieve a list of catalog IDs for DCCs

### ISSUE THREAD

**Issue by victor73** [nih-cfde/dashboard-api#3]
In order for an interface to display the list of pending submissions from a DCC, the API should provide an endpoint to make the retrieval of that data from deriva possible. The endpoint should accept a parameter for which DCC is being queried and possibly additional optional parameters to limit the results of the query by date (eg. retrieve the submissions in the last 90 days), or by status (retrieve only the approved submissions, or retrieve only the pending submissions).

**Comment by ACharbonneau** [comment]
Did this get finished? Or should it move to the epic 2 technical debt?

**Comment by RLC-DCPPC** [comment]
Hi @victor73. What's the status of this item?

**Comment by jonathancrabtree** [comment]
I'm not sure what other extant issue depends on this one, but it definitely has not been done and (IMO) it does not belong in Epic 2 technical debt. As Lee noted, the functionality was handled by DERIVA/Chaise in that epic. As an aside, it should be a trivial query of the registry database, but I'm not sure what it would be used for, unless we intend to include summary information about a DCC's submissions on the Personalized Dashboard (i.e., for someone in an appropriate DCC-associated or CFDE-associated role.)

**Comment by RLC-DCPPC** [comment]
This is blocking [Epic 2 ](https://github.com/nih-cfde/planning-docs/issues/73) atm (rightly or wrongly). So, if we still want it, let's attach it to something else; if OBE, let's close it.

**Comment by victor73** [comment]
Let's move it to Epic 3 then...

**Comment by victor73** [comment]
Moved...

**Comment by ACharbonneau** [comment]
I'm closing this.
