### ISSUE TITLE
Convert dashboard-api code from StatsQuery to StatsQuery2

### ISSUE THREAD

**Issue by jonathancrabtree** [nih-cfde/dashboard-api#39]
Figure out the implications (for the API) of using the new core fact tables instead of the original level1 stats tables. This will also have to be looked at in the presentation layer/dashboard.

**Comment by karlcz** [comment]
The core\_fact rows, like level1\_stats represent a set of entities summarized by counts. The structural shift is that they are labeled by a _set_ of term IDs for each dimension (encoded as an array) rather than a single term IDs.

In both tables, a set is known by its distinct combination of labels across all dimensions. By generalizing each dimension's label to be a set of term IDs, we handle two scenarios within the same structure:
1. The entities labeled directly by a foreign key, e.g. a file's file\_format will have zero or one term IDs
2. The entities labeled indirectly by associated content, e.g. a file's anatomy will have zero or more term IDs

These entity sets become disjoint, so a specific file, biosample, subject, or collection is only counted once among all core\_fact rows.

**Comment by jonathancrabtree** [comment]
The initial StatsQuery2 conversion is using `fetch_flattened` and this seems to work pretty well in most cases given our current release catalog. There's still some double-counting due to the flattening but much much less than before.

**Comment by jonathancrabtree** [comment]
Representative figures from app-dev using the old StatsQuery counts:

![Screen Shot 2023-02-08 at 10 48 28 AM](https://user-images.githubusercontent.com/5394345/217580789-2cd8098d-d2ff-4118-a0ae-4b429fb1b967.png)
![Screen Shot 2023-02-08 at 10 48 43 AM](https://user-images.githubusercontent.com/5394345/217580794-143f98d7-3efb-4257-9343-d33792727698.png)
![Screen Shot 2023-02-08 at 10 49 03 AM](https://user-images.githubusercontent.com/5394345/217580798-32ac739f-64ae-4011-922d-e500d41ea614.png)
![Screen Shot 2023-02-08 at 10 49 20 AM](https://user-images.githubusercontent.com/5394345/217580800-0ea44db9-ce67-4baa-83ff-e8568121ba5c.png)
![Screen Shot 2023-02-08 at 10 49 58 AM](https://user-images.githubusercontent.com/5394345/217580802-3f057f9d-0cbb-4994-8aa3-da3cfb101e12.png)
![Screen Shot 2023-02-08 at 10 50 16 AM](https://user-images.githubusercontent.com/5394345/217580803-d25bd99f-31a5-4bb5-a18e-d88da581dacd.png)
![Screen Shot 2023-02-08 at 10 50 50 AM](https://user-images.githubusercontent.com/5394345/217580805-ef2b5478-b0a3-4cba-94ff-794ee0556606.png)
![Screen Shot 2023-02-08 at 10 50 59 AM](https://user-images.githubusercontent.com/5394345/217580806-355eb6d2-4fe6-4fc0-bec4-00f7798d7ecd.png)
![Screen Shot 2023-02-08 at 10 51 09 AM](https://user-images.githubusercontent.com/5394345/217580808-5c3a95d9-9203-4dca-9058-fd581811e818.png)
![Screen Shot 2023-02-08 at 10 51 31 AM](https://user-images.githubusercontent.com/5394345/217580815-d5b9c432-35f8-4b72-88ab-b2d2b3048789.png)

**Comment by jonathancrabtree** [comment]
Switching from level1 stats to StatsQuery2 drastically reduces the numbers in all of these plots, in many cases down to the correct total or close to it:

![Screen Shot 2023-02-08 at 3 46 06 PM](https://user-images.githubusercontent.com/5394345/217648062-08cc6dce-4df8-45e1-8f2a-70441bd7d029.png)
![Screen Shot 2023-02-08 at 3 46 23 PM](https://user-images.githubusercontent.com/5394345/217648065-223eec79-29aa-4a52-b602-fed4488545c6.png)
![Screen Shot 2023-02-08 at 3 46 38 PM](https://user-images.githubusercontent.com/5394345/217648068-bf2a1fca-3ff6-48ef-9671-e737ca54e37f.png)
![Screen Shot 2023-02-08 at 3 47 00 PM](https://user-images.githubusercontent.com/5394345/217648071-d72a8722-f105-4264-84c7-aa869c28b676.png)
![Screen Shot 2023-02-08 at 3 47 30 PM](https://user-images.githubusercontent.com/5394345/217648072-b3ea950e-aba8-41bd-98b5-b9aee47f980e.png)
![Screen Shot 2023-02-08 at 3 47 51 PM](https://user-images.githubusercontent.com/5394345/217648074-632d218a-3434-49aa-8e67-b9e7ee7b133b.png)
![Screen Shot 2023-02-08 at 3 48 33 PM](https://user-images.githubusercontent.com/5394345/217648076-8e72c33c-e167-4223-905a-c7d4c83ce7d3.png)
![Screen Shot 2023-02-08 at 3 48 48 PM](https://user-images.githubusercontent.com/5394345/217648078-1961da6f-b35b-42ef-8c79-5dd7dccdd428.png)
![Screen Shot 2023-02-08 at 3 49 32 PM](https://user-images.githubusercontent.com/5394345/217648080-0081f27c-e0d6-4e08-b9bb-d3f86f47041c.png)

**Comment by jonathancrabtree** [comment]
dashboard-api now uses StatsQuery2 instead of StatsQuery and this version is live on app-dev (but still with the 3rd dimension on the graphs.)
